services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda start
      - --overprovisioned
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --node-id 0
      - --check=false
      - --pandaproxy-addr 0.0.0.0:8082
      - --kafka-addr 0.0.0.0:9092
      - --advertise-kafka-addr redpanda:9092
    ports:
      - "9092:9092"
  mongo:
    image: mongo:8.0.5
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=books
    ports:
      - "27017:27017"
  book-service:
    image: ghcr.io/wingi11/book-service
    build:
      context: ./book-service
      dockerfile: ./src/main/docker/Dockerfile
    container_name: book-service
    environment:
      - QUARKUS_KAFKA_BOOTSTRAP_SERVERS=redpanda:9092
      - QUARKUS_MONGODB_CONNECTION_STRING=mongodb://mongo:27017/?retryWrites=false
      - QUARKUS_MONGODB_DATABASE=books
      - QUARKUS_SWAGGER_UI_ALWAYS_INCLUDE=true
      - MP_MESSAGING_OUTGOING_CHECKOUT_REQUEST_CONNECTOR=smallrye-kafka
      - MP_MESSAGING_OUTGOING_CHECKOUT_REQUEST_TOPIC=checkout-request
      - MP_MESSAGING_OUTGOING_CHECKOUT_REQUEST_VALUE_SERIALIZER=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      - MP_MESSAGING_INCOMING_CHECKOUT_RESPONSE_CONNECTOR=smallrye-kafka
      - MP_MESSAGING_INCOMING_CHECKOUT_RESPONSE_TOPIC=checkout-response
      - JAVA_NET_PREFER_IPV4_STACK=true
      # OTEL
      - QUARKUS_OTEL_ENABLED=true
      - QUARKUS_OTEL_LOGS_ENABLED=true
      - QUARKUS_OTEL_METRICS_ENABLED=true
      - QUARKUS_OTEL_SERVICE_NAME=book-service
      - QUARKUS_OTEL_EXPORTER_OTLP_ENDPOINT=http://lgtm:4317
    depends_on:
      - redpanda
      - mongo
    ports:
      - "8080:8080"
  checkout-service:
    image: ghcr.io/wingi11/checkout-service
    build:
      context: ./checkout-service
      dockerfile: ./src/main/docker/Dockerfile
    container_name: checkout-service
    environment:
      - QUARKUS_KAFKA_BOOTSTRAP_SERVERS=redpanda:9092
      - QUARKUS_HTTP_PORT=8081
      - MP_MESSAGING_OUTGOING_CHECKOUT_RESPONSE_CONNECTOR=smallrye-kafka
      - MP_MESSAGING_OUTGOING_CHECKOUT_RESPONSE_TOPIC=checkout-response
      - MP_MESSAGING_OUTGOING_CHECKOUT_RESPONSE_VALUE_SERIALIZER=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      - MP_MESSAGING_INCOMING_CHECKOUT_REQUEST_CONNECTOR=smallrye-kafka
      - MP_MESSAGING_INCOMING_CHECKOUT_REQUEST_TOPIC=checkout-request
      - JAVA_NET_PREFER_IPV4_STACK=true
      # OTEL
      - QUARKUS_OTEL_ENABLED=true
      - QUARKUS_OTEL_LOGS_ENABLED=true
      - QUARKUS_OTEL_METRICS_ENABLED=true
      - QUARKUS_OTEL_SERVICE_NAME=checkout-service
      - QUARKUS_OTEL_EXPORTER_OTLP_ENDPOINT=http://lgtm:4317
    depends_on:
      - redpanda
      - mongo
    ports:
      - "8081:8081"
  lgtm:
    image: grafana/otel-lgtm
    ports:
      - 3000:3000
      - 4317:4317
      - 4318:4318
