{
 "title": "Stats",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Successful Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(http_server_request_duration_seconds_count{http_response_status_code=~\"200|202|400|404\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Failed requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "sum(http_server_request_duration_seconds_count{http_response_status_code=~\"500|502\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "sum by() (rate(http_server_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Book Service Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(detected_level) (rate({service_name=\"book-service\"} [1m]))",
     "legendFormat": "{{detected_level}}"
    }
   ]
  },
  {
   "title": "Checkout Service Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(detected_level) (rate({service_name=\"checkout-service\"} [1m]))",
     "legendFormat": "{{detected_level}}"
    }
   ]
  },
  {
   "title": "Kafka Service Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(detected_level) (rate({service_name=\"kafka\"} [5m]))",
     "legendFormat": "{{detected_level}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg(jvm_memory_used_bytes{} * on (job, instance) group_left(container_id,host_arch,host_name,os_description,os_type,process_command_args,process_executable_path,process_pid,process_runtime_description,process_runtime_name,process_runtime_version,telemetry_distro_name,telemetry_distro_version,telemetry_sdk_language,telemetry_sdk_name,telemetry_sdk_version) topk by (job, instance) (1, target_info{}))",
     "legendFormat": "Usage in Bytes"
    }
   ]
  },
  {
   "title": "Last traces",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "filters": [
      { "id": "d6ee42f6", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  }
 ]
}